# Generated by Django 3.2.9 on 2024-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_totalunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='isUnit',
            field=models.BooleanField(default=False),
        ),
    ]
