# Generated by Django 3.2.9 on 2024-05-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240501_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isCooking',
            field=models.BooleanField(default=False),
        ),
    ]
