# Generated by Django 3.2.9 on 2024-05-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_iscooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='orders',
            field=models.ManyToManyField(related_name='orders', to='app.Order'),
        ),
    ]
