# Generated by Django 3.2.9 on 2024-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240419_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='isavaliable',
            field=models.BooleanField(default=True),
        ),
    ]
