# Generated by Django 3.2.9 on 2024-04-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_food_isavaliable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodintegrient',
            old_name='unit',
            new_name='useunit',
        ),
    ]
