# Generated by Django 3.2.9 on 2024-05-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderdetail_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='food_orders',
            field=models.ManyToManyField(related_name='food_orders', to='app.FoodOrder'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_orders',
            field=models.ManyToManyField(related_name='product_orders', to='app.FoodOrder'),
        ),
    ]
