# Generated by Django 3.2.9 on 2024-04-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_floor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
