# Generated by Django 3.2.9 on 2024-05-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_realorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realorder',
            name='end_cooking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realorder',
            name='start_cooking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
