# Generated by Django 3.2.9 on 2024-05-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240505_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
    ]
