# Generated by Django 3.2.9 on 2024-05-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderdetail_isorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='realorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
