# Generated by Django 3.2.9 on 2024-05-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_realorder_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realorder',
            old_name='is_paid',
            new_name='isPaid',
        ),
    ]
