# Generated by Django 3.2.9 on 2024-05-17 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_is_paid_realorder_ispaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveVoucherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originaltotalPrice', models.CharField(blank=True, max_length=10, null=True)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery', models.CharField(blank=True, max_length=10, null=True)),
                ('totalPrice', models.CharField(blank=True, max_length=10, null=True)),
                ('totalProfit', models.CharField(blank=True, max_length=10, null=True)),
                ('totalPayment', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_name', to='app.table'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realorder',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orderdetail'),
        ),
    ]
