# Generated by Django 3.2.9 on 2024-05-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20240517_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='savevoucherhistory',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='savevoucherhistory',
            name='payment_type',
            field=models.CharField(default='Cash', max_length=10),
        ),
    ]
