# Generated by Django 3.2.9 on 2024-05-18 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20240518_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savevoucherhistory',
            name='totalProfit',
        ),
        migrations.AddField(
            model_name='realorder',
            name='originaltotalPrice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='realorder',
            name='totalPayment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='realorder',
            name='totalProfit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='savevoucherhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
