# Generated by Django 3.2.9 on 2024-05-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20240518_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='profit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
