# Generated by Django 3.2.9 on 2024-05-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20240518_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savevoucherhistory',
            name='order',
        ),
        migrations.AddField(
            model_name='savevoucherhistory',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='app.RealOrder'),
        ),
    ]
