# Generated by Django 3.2.9 on 2024-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_realorder_totalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='customername',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='deliveryCharges',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='isDelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='phoneno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
