# Generated by Django 3.2.9 on 2024-05-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20240522_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('phoneno', models.CharField(default='', max_length=10)),
                ('deliveryCharges', models.CharField(default=0, max_length=10)),
                ('customername', models.CharField(default='', max_length=10)),
                ('exceptTime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='customername',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='deliveryCharges',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='deliveryorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='app.deliveryorder'),
        ),
    ]
