# Generated by Django 3.2.9 on 2024-05-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20240525_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customername',
            name='user',
        ),
        migrations.AlterField(
            model_name='customername',
            name='sales',
            field=models.ManyToManyField(related_name='sales', to='app.SaveVoucherHistory'),
        ),
    ]
