# Generated by Django 3.2.9 on 2024-06-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_wasteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteproduct',
            name='cost',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
